controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\data\ActiveDataProvider;
use yii\data\SqlDataProvider;
use yii\db\conditions\BetweenCondition;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    
    public function actionConsulta1a() {

        $dataProvider = new SqlDataProvider([
            'sql' => 'SELECT nombre_champ as campeón , COUNT(*)as NºBaneos FROM campeones c INNER JOIN banean b ON c.codigo_campeon = b.codigo_campeon GROUP BY c.nombre_champ ORDER BY NºBaneos DESC  ',
            'pagination' => [
                'pagesize' => 5,
            ]
        ]);

        return $this->render("resultado", [
                    "resultados" => $dataProvider,
                    "campos" => ['campeón', 'NºBaneos'],
                    "titulo" => "Número de veces baneado cada campeón",
                    "sql" => "SELECT nombre_champ , COUNT(*) as NºBaneos FROM campeones c INNER JOIN banean b ON c.codigo_campeon = b.codigo_campeon GROUP BY c.nombre_champ ORDER BY NºBaneos DESC  ",
        ]);
    }
    
     public function actionConsulta2a() {

        $dataProvider = new SqlDataProvider([
            'sql' => 'SELECT nombre_champ as campeón , COUNT(*)as NºPickeos FROM campeones c INNER JOIN pickean p ON c.codigo_campeon = p.codigo_campeon GROUP BY c.nombre_champ ORDER BY NºPickeos DESC  ',
            'pagination' => [
                'pagesize' => 5,
            ]
        ]);

        return $this->render("resultado", [
                    "resultados" => $dataProvider,
                    "campos" => ['campeón', 'NºPickeos'],
                    "titulo" => "Número de veces pickeado cada campeón",
                    "sql" => "SELECT nombre_champ as campeón , COUNT(*)as NºPickeos FROM campeones c INNER JOIN pickean p ON c.codigo_campeon = p.codigo_campeon GROUP BY c.nombre_champ ORDER BY NºPickeos DESC",
        ]);
    }
    
     public function actionConsulta3a() {

        $dataProvider = new SqlDataProvider([
            'sql' => 'SELECT nombre_e Equipo, COUNT(*) Victorias FROM equipos e INNER JOIN juegan j ON e.codigo_equipo = j.codigo_equipo WHERE j.destruccion_nexo=1 GROUP BY e.codigo_equipo ORDER BY Victorias DESC ',
            'pagination' => [
                'pagesize' => 5,
            ]
        ]);

        return $this->render("resultado", [
                    "resultados" => $dataProvider,
                    "campos" => ['Equipo', 'Victorias'],
                    "titulo" => "Clasificación",
                    "sql" => "SELECT nombre_e Equipo, COUNT(*) Victorias FROM equipos e INNER JOIN juegan j ON e.codigo_equipo = j.codigo_equipo WHERE j.destruccion_nexo=1 GROUP BY e.codigo_equipo ORDER BY Victorias DESC",
        ]);
    }
   
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use rmrevin\yii\fontawesome\FA;
use kv4nt\owlcarousel\OwlCarouselWidget;
use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */

$this->title = 'LigaLOL';
?>
<html lang="es">
    <head>
        <title>Bootstrap Example</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

<!--        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>-->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </head>
    <body>

        <div class="container-fluid">
            <div id="myCarousel" class="carousel slide" data-ride="carousel" style="margin-top: 70px;">
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                    <li data-target="#myCarousel" data-slide-to="3"></li>
                </ol>

                <div class="carousel-inner">
                    <div class="item active">
                        <img src="../web/img/redbull.png" alt="RedBull" style="width:100%;">
                    </div>

                    <div class="item">
                        <img src="../web/img/banner.jpg" alt="Chicago" style="width:100%;">
                    </div>

                    <div class="item">
                        <img src="../web/img/banner2.jpg" alt="Chicago" style="width:100%;">
                    </div>

                    <div class="item">
                        <img src="../web/img/banner4.jpg" alt="Chicago" style="width:100%;">
                    </div>
                </div>

                <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                    <span class="sr-only">Anterior</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                    <span class="sr-only">Siguiente</span>
                </a>
            </div>

        </div>
        <div class="container-home"style="margin-bottom: 30px;">
            <div class="container-carts" style="margin-bottom: 20px;">
                <div class="card">
                    <div class="face face1"style="padding-bottom: 40px;">
                        <div class="content">
                            <img src="../web/img/campeonhome.png" style="margin-left: 8px;">
                            <h3 style="
    margin-top: 10px;
    padding-top: 0px;
">Campeones</h3>
                        </div>
                    </div>
                    <div class="face face2" style="padding-bottom: 40px;">
                        <div class="content">
                            <?= Html::a('Administrar Campeones', ['/campeones/index']) ?>
                           <?= Html::a('Campeones más baneados', ['site/consulta1a']) ?>
                            <?= Html::a('Campeones más pickeados', ['site/consulta2a']) ?>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="face face1">
                        <div class="content">
                            <img src="../web/img/jugadores(1).png" style="margin-left: 8px;">
                            <h3>Jugadores</h3>
                        </div>
                    </div>
                    <div class="face face2">
                        <div class="content">
                            <?= Html::a('Administrar Jugadores  ', ['/jugadores/index']) ?>
                        

                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="face face1">
                        <div class="content">
                            <img src="../web/img/escudohome.png">
                            <h3>Equipos</h3>
                        </div>
                    </div>
                    <div class="face face2">
                        <div class="content">
                             <?= Html::a('Administrar Equipos  ', ['/equipos/index']) ?>
                             <?= Html::a('Clasificación  ', ['/site/consulta3a']) ?>
                        </div>
                    </div>
                </div>


            </div>
        </div>
        <div><p></p>
            <p></p>
            <p></p>
        </div>

        <div class="container-home">
            <div class="container-carts" style="top:-70px;margin-bottom: 35px;">
                <div class="card">
                    <div class="face face1">
                        <div class="content">
                            <img src="../web/img/patrocinadores.png" style="margin-left: 20px;">
                            <h3>Patrocinadores</h3>
                        </div>
                    </div>
                    <div class="face face2">
                        <div class="content">
                            <?= Html::a('Administrar Patrocinadores  ', ['/patrocinadores/index']) ?>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="face face1">
                        <div class="content">
                            <img src="../web/img/partidoshome.png" >
                            <h3>Partidos</h3>
                        </div>
                    </div>
                    <div class="face face2">
                        <div class="content">

                           <?= Html::a('Administrar Partidos  ', ['/partidos/index']) ?>
                            <?= Html::a('Administrar Picks  ', ['/pickean/index']) ?>
                            <?= Html::a('Administrar Bans  ', ['/banean/index']) ?>
                            <?= Html::a('Administrar Datos Partidos  ', ['/juegan/index']) ?>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="face face1">
                        <div class="content">
                            <img src="../web/img/entrenadorhome.png"style="margin-left: 8px;">
                            <h3>Entrenadores</h3>
                        </div>
                    </div>
                    <div class="face face2">
                        <div class="content">
                             <?= Html::a('Administrar Entrenadores  ', ['/entrenadores/index']) ?>
                            
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/resultado.php
<?php

use yii\grid\GridView;
?>
<div class="consultas">
    <h2><?= $titulo ?></h2>
    
</div>
<?= GridView:: widget ([
'dataProvider' => $resultados,
 'columns'=>$campos
]); ?>